# Generated by Django 3.0.1 on 2020-01-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='userprofile',
        ),
    ]
